### ISSUE TITLE
Switch from `<style lang="less">` to `style.less { }` for inline component styles

### ISSUE THREAD

**Issue by patrick-steele-idem** [marko-js/marko#548]
We no longer want to hijack the standard HTML `<style>` tag to avoid confusion and future problems. Instead, we will use the following:

```css
style {
    .foo {
        background-color: 'red';
    }
}
<div>Hello World</div>
```

Or, with a specific CSS preprocessor language:

```css
style.less {
    .foo {
        background-color: 'red';
    }
}
<div>Hello World</div>
```
