### ISSUE TITLE
Don't generate meta propertys when multiple root elements exists

### ISSUE THREAD

**Issue by StarpTech** [marko-js/marko#717]
### Context
Multi file components

### Expected Behavior
In the browser no component-browser is fetched

### Actual Behavior
Marko compiler dont generate meta fields so no `deps` are required.

### Possible Fix
Wrap the component template in a container so that there is only one root element.

### Your Environment
Windows 10
Marko 4.4.9

### Steps to Reproduce

browser.json
```
{
    "dependencies": [
        "./style.less"
    ]
}
```
component-browser.js
```js
console.log('test')
```

index.marko
```marko
<div id="video"></div>
<div class="buttons-wrapper">
<button id="button-play-gum" class="button-demo" href="#">Start Streaming</button>
<button id="button-stop-gum" class="button-demo" href="#">Stop Streaming</button>
</div>
```

style.less
```css
h1 {
  text-align: center;
}

.buttons-wrapper {
  text-align: center;
}

.hidden {
  display: none;
}

#video {
  display: block;
  width: 100%;
}

.button-demo {
  padding: 0.5em;
  display: inline-block;
  margin: 1em auto;
}

.author {
  display: block;
  margin-top: 1em;
}
```

## Produced

index.marko.js
```
marko_template.meta = {};
```

## Expected output
index.marko.js
```
marko_template.meta = {
    deps: [
      "./style.less",
      {
          type: "require",
          path: "./component-browser"
        },
      {
          type: "require",
          path: "marko/src/components"
        }
    ]
  };
```
